DROP TABLE IF EXISTS USER_TB RESTRICT;
DROP TABLE IF EXISTS MESSAGE_TB RESTRICT;
DROP TABLE IF EXISTS UserToUser_TB RESTRICT;

CREATE TABLE USER_TB (
	USERID   VARCHAR(30) NOT NULL,
	NAME     VARCHAR(30) NOT NULL,
	EMAIL    VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	INTRODUCTION VARCHAR(300) NULL,
	REGION       VARCHAR(50)  NULL,
	HOMEPAGE     VARCHAR(80)  NULL,
	IMG_FILE     VARCHAR(100) NULL,
	IMG_TYPE     VARCHAR(50)  NULL 
);

ALTER TABLE USER_TB
	ADD CONSTRAINT PK_USER_TB
		PRIMARY KEY (
			USERID
		);

CREATE TABLE MESSAGE_TB (
	MSG_NO   INTEGER      NOT NULL,
	CONTENTS VARCHAR(500) NOT NULL,
	WRITER   VARCHAR(30)  NOT NULL,
	REG_DT   TIMESTAMP    NULL
);

ALTER TABLE MESSAGE_TB
	ADD CONSTRAINT PK_MESSAGE_TB
		PRIMARY KEY (
			MSG_NO
		);

ALTER TABLE MESSAGE_TB
	MODIFY COLUMN MSG_NO INTEGER NOT NULL AUTO_INCREMENT;

CREATE TABLE UserToUser_TB (
	WHO  VARCHAR(30) NOT NULL,
	WHOM VARCHAR(30) NOT NULL
);

ALTER TABLE UserToUser_TB
	ADD CONSTRAINT PK_UserToUser_TB
		PRIMARY KEY (
			WHO,
			WHOM
		);

ALTER TABLE MESSAGE_TB
	ADD CONSTRAINT FK_USER_TB_TO_MESSAGE_TB
		FOREIGN KEY (
			WRITER
		)
		REFERENCES USER_TB (
			USERID
		);